"""initial schema

Revision ID: 001
Revises: 
Create Date: 2026-05-21 09:55:41.410229

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.execute("CREATE SCHEMA IF NOT EXISTS core")
    op.execute("CREATE SCHEMA IF NOT EXISTS events")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_ldap', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('admin', 'analyst')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False, schema='auth', postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_users_username', 'users', ['username'], unique=False, schema='auth')
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.BigInteger(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('idx_audit_action', 'audit_log', ['action', sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_index('idx_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False, schema='auth')
    op.create_index('idx_audit_user', 'audit_log', ['user_id', sa.literal_column('created_at DESC')], unique=False, schema='auth')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='auth'
    )
    op.create_index('idx_refresh_tokens_expires', 'refresh_tokens', ['expires_at'], unique=False, schema='auth')
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False, schema='auth')
    op.create_table('global_role_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name'),
    schema='core'
    )
    op.create_table('projects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_projects_active', 'projects', ['is_deleted'], unique=False, schema='core', postgresql_where=sa.text('is_deleted = false'))
    op.create_index('idx_projects_created_by', 'projects', ['created_by'], unique=False, schema='core')
    op.create_table('physical_datasets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('total_events', sa.Integer(), nullable=False),
    sa.Column('total_cases', sa.Integer(), nullable=False),
    sa.Column('unique_activities', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=False),
    sa.Column('health_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='ready', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.CheckConstraint("health_status IN ('good', 'warning', 'poor')", name='ck_physical_datasets_health_status'),
    sa.CheckConstraint("status IN ('uploading', 'validating', 'ready', 'failed')", name='ck_physical_datasets_status'),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_physical_datasets_project', 'physical_datasets', ['project_id'], unique=False, schema='core')
    op.create_index('idx_physical_datasets_status', 'physical_datasets', ['status'], unique=False, schema='core')
    op.create_table('role_mappings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default='Основной маппинг', nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'version', name='uq_role_mappings_project_version'),
    schema='core'
    )
    op.create_index('idx_role_mappings_project', 'role_mappings', ['project_id', sa.literal_column('version DESC')], unique=False, schema='core')
    op.create_table('sla_rules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('operation_pattern', sa.String(length=500), nullable=False),
    sa.Column('sla_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sla_unit', sa.String(length=20), nullable=False),
    sa.Column('tolerance_hours', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('target_compliance_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('90.0'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sla_unit IN ('workdays', 'calendar_days', 'workhours', 'hours')", name='ck_sla_rules_unit'),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_sla_rules_effective', 'sla_rules', ['effective_from', 'effective_until'], unique=False, schema='core')
    op.create_index('idx_sla_rules_project', 'sla_rules', ['project_id'], unique=False, schema='core')
    op.create_index('idx_sla_rules_role', 'sla_rules', ['project_id', 'role'], unique=False, schema='core')
    op.create_table('upload_templates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), server_default='Стандартный шаблон', nullable=False),
    sa.Column('column_mapping', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_upload_templates_project', 'upload_templates', ['project_id'], unique=False, schema='core')
    op.create_table('virtual_datasets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('project_id', sa.BigInteger(), nullable=False),
    sa.Column('physical_dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role_mapping_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sla_rules_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('cached_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_personal', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['physical_dataset_id'], ['core.physical_datasets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['core.projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_virtual_datasets_owner', 'virtual_datasets', ['created_by'], unique=False, schema='core')
    op.create_index('idx_virtual_datasets_physical', 'virtual_datasets', ['physical_dataset_id'], unique=False, schema='core')
    op.create_index('idx_virtual_datasets_project', 'virtual_datasets', ['project_id'], unique=False, schema='core')
    op.create_table('event_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('physical_dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('case_id', sa.String(length=255), nullable=False),
    sa.Column('activity', sa.String(length=500), nullable=False),
    sa.Column('timestamp_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timestamp_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('own_duration_sec', sa.BigInteger(), sa.Computed('EXTRACT(EPOCH FROM (timestamp_end - timestamp_start))::bigint', persisted=True), nullable=False),
    sa.ForeignKeyConstraint(['physical_dataset_id'], ['core.physical_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='events'
    )
    op.create_index('idx_event_log_activity', 'event_log', ['physical_dataset_id', 'activity'], unique=False, schema='events')
    op.create_index('idx_event_log_attrs_gin', 'event_log', ['attributes'], unique=False, schema='events', postgresql_using='gin')
    op.create_index('idx_event_log_case', 'event_log', ['physical_dataset_id', 'case_id'], unique=False, schema='events')
    op.create_index('idx_event_log_case_time', 'event_log', ['physical_dataset_id', 'case_id', 'timestamp_start'], unique=False, schema='events')
    op.create_index('idx_event_log_dataset', 'event_log', ['physical_dataset_id'], unique=False, schema='events')
    op.create_index('idx_event_log_dept', 'event_log', ['physical_dataset_id', 'department'], unique=False, schema='events')
    op.create_index('idx_event_log_resource', 'event_log', ['physical_dataset_id', 'resource'], unique=False, schema='events')
    op.create_index('idx_event_log_time_start', 'event_log', ['physical_dataset_id', 'timestamp_start'], unique=False, schema='events')
    op.create_table('annotations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('virtual_dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.String(length=500), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("target_type IN ('node', 'edge', 'case', 'time_range')", name='ck_annotations_target_type'),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['virtual_dataset_id'], ['core.virtual_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_annotations_dataset', 'annotations', ['virtual_dataset_id'], unique=False, schema='core')
    op.create_index('idx_annotations_target', 'annotations', ['target_type', 'target_id'], unique=False, schema='core')
    op.create_table('named_slices',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('virtual_dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['virtual_dataset_id'], ['core.virtual_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_named_slices_dataset', 'named_slices', ['virtual_dataset_id'], unique=False, schema='core')
    op.create_table('dashboards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('virtual_dataset_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('global_filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('applied_slice_id', sa.BigInteger(), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_slice_id'], ['core.named_slices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['auth.users.id'], ),
    sa.ForeignKeyConstraint(['virtual_dataset_id'], ['core.virtual_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_dashboards_dataset', 'dashboards', ['virtual_dataset_id'], unique=False, schema='core')
    op.create_index('idx_dashboards_owner', 'dashboards', ['created_by'], unique=False, schema='core')
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('dashboard_id', sa.BigInteger(), nullable=False),
    sa.Column('widget_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('local_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('use_global_filters', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('grid_x', sa.Integer(), nullable=False),
    sa.Column('grid_y', sa.Integer(), nullable=False),
    sa.Column('grid_width', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('grid_height', sa.Integer(), server_default=sa.text('3'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['core.dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_widgets_dashboard', 'dashboard_widgets', ['dashboard_id'], unique=False, schema='core')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_widgets_dashboard', table_name='dashboard_widgets', schema='core')
    op.drop_table('dashboard_widgets', schema='core')
    op.drop_index('idx_dashboards_owner', table_name='dashboards', schema='core')
    op.drop_index('idx_dashboards_dataset', table_name='dashboards', schema='core')
    op.drop_table('dashboards', schema='core')
    op.drop_index('idx_named_slices_dataset', table_name='named_slices', schema='core')
    op.drop_table('named_slices', schema='core')
    op.drop_index('idx_annotations_target', table_name='annotations', schema='core')
    op.drop_index('idx_annotations_dataset', table_name='annotations', schema='core')
    op.drop_table('annotations', schema='core')
    op.drop_index('idx_event_log_time_start', table_name='event_log', schema='events')
    op.drop_index('idx_event_log_resource', table_name='event_log', schema='events')
    op.drop_index('idx_event_log_dept', table_name='event_log', schema='events')
    op.drop_index('idx_event_log_dataset', table_name='event_log', schema='events')
    op.drop_index('idx_event_log_case_time', table_name='event_log', schema='events')
    op.drop_index('idx_event_log_case', table_name='event_log', schema='events')
    op.drop_index('idx_event_log_attrs_gin', table_name='event_log', schema='events', postgresql_using='gin')
    op.drop_index('idx_event_log_activity', table_name='event_log', schema='events')
    op.drop_table('event_log', schema='events')
    op.drop_index('idx_virtual_datasets_project', table_name='virtual_datasets', schema='core')
    op.drop_index('idx_virtual_datasets_physical', table_name='virtual_datasets', schema='core')
    op.drop_index('idx_virtual_datasets_owner', table_name='virtual_datasets', schema='core')
    op.drop_table('virtual_datasets', schema='core')
    op.drop_index('idx_upload_templates_project', table_name='upload_templates', schema='core')
    op.drop_table('upload_templates', schema='core')
    op.drop_index('idx_sla_rules_role', table_name='sla_rules', schema='core')
    op.drop_index('idx_sla_rules_project', table_name='sla_rules', schema='core')
    op.drop_index('idx_sla_rules_effective', table_name='sla_rules', schema='core')
    op.drop_table('sla_rules', schema='core')
    op.drop_index('idx_role_mappings_project', table_name='role_mappings', schema='core')
    op.drop_table('role_mappings', schema='core')
    op.drop_index('idx_physical_datasets_status', table_name='physical_datasets', schema='core')
    op.drop_index('idx_physical_datasets_project', table_name='physical_datasets', schema='core')
    op.drop_table('physical_datasets', schema='core')
    op.drop_index('idx_projects_created_by', table_name='projects', schema='core')
    op.drop_index('idx_projects_active', table_name='projects', schema='core', postgresql_where=sa.text('is_deleted = false'))
    op.drop_table('projects', schema='core')
    op.drop_table('global_role_templates', schema='core')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens', schema='auth')
    op.drop_index('idx_refresh_tokens_expires', table_name='refresh_tokens', schema='auth')
    op.drop_table('refresh_tokens', schema='auth')
    op.drop_index('idx_audit_user', table_name='audit_log', schema='auth')
    op.drop_index('idx_audit_entity', table_name='audit_log', schema='auth')
    op.drop_index('idx_audit_action', table_name='audit_log', schema='auth')
    op.drop_table('audit_log', schema='auth')
    op.drop_index('idx_users_username', table_name='users', schema='auth')
    op.drop_index('idx_users_active', table_name='users', schema='auth', postgresql_where=sa.text('is_active = true'))
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS events CASCADE")
    op.execute("DROP SCHEMA IF EXISTS core CASCADE")
    op.execute("DROP SCHEMA IF EXISTS auth CASCADE")
